name: Update GitHub Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate contribution card
        uses: seijikohara/profile-cards-action@v1
        with:
          github-token: ${{ github.token }}
          username: Vedp9984
          cards: contributions
          output-dir: assets
          themes: light,dark
          commit: true
